CREATE USER C##BD_SAKILA IDENTIFIED BY 1234
TEMPORARY TABLESPACE TEMP
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION,CREATE ANY TABLE, DROP ANY TABLE, ALTER ANY TABLE TO C##BD_SAKILA;
GRANT CREATE PROCEDURE, DROP ANY PROCEDURE, ALTER ANY PROCEDURE, CREATE TRIGGER, DROP ANY TRIGGER, ALTER ANY TRIGGER, CREATE SEQUENCE, DROP ANY SEQUENCE, ALTER ANY SEQUENCE, CREATE VIEW, DROP ANY VIEW  TO C##BD_SAKILA;

    